
services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed, NGINX REVERSE-PROXY"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t new-reverseproxy .
  - docker tag new-reverseproxy samnzay/new-reverseproxy:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push samnzay/new-reverseproxy:v1